require 'test_helper'

class DeliverySlipDetailMiddleClassificationsControllerTest < ActionController::TestCase
  setup do
    @delivery_slip_detail_middle_classification = delivery_slip_detail_middle_classifications(:one)
  end

  test "should get index" do
    get :index
    assert_response :success
    assert_not_nil assigns(:delivery_slip_detail_middle_classifications)
  end

  test "should get new" do
    get :new
    assert_response :success
  end

  test "should create delivery_slip_detail_middle_classification" do
    assert_difference('DeliverySlipDetailMiddleClassification.count') do
      post :create, delivery_slip_detail_middle_classification: { accessory_cost: @delivery_slip_detail_middle_classification.accessory_cost, delivery_slip_detail_large_classification_id: @delivery_slip_detail_middle_classification.delivery_slip_detail_large_classification_id, delivery_slip_header_id: @delivery_slip_detail_middle_classification.delivery_slip_header_id, delivery_slip_item_division_id: @delivery_slip_detail_middle_classification.delivery_slip_item_division_id, delivery_slip_price: @delivery_slip_detail_middle_classification.delivery_slip_price, execution_price: @delivery_slip_detail_middle_classification.execution_price, execution_quantity: @delivery_slip_detail_middle_classification.execution_quantity, execution_unit_price: @delivery_slip_detail_middle_classification.execution_unit_price, labor_cost_total: @delivery_slip_detail_middle_classification.labor_cost_total, labor_productivity_unit: @delivery_slip_detail_middle_classification.labor_productivity_unit, labor_productivity_unit_total: @delivery_slip_detail_middle_classification.labor_productivity_unit_total, labor_unit_price: @delivery_slip_detail_middle_classification.labor_unit_price, line_number: @delivery_slip_detail_middle_classification.line_number, material_cost_total: @delivery_slip_detail_middle_classification.material_cost_total, material_id: @delivery_slip_detail_middle_classification.material_id, material_id: @delivery_slip_detail_middle_classification.material_id, material_quantity: @delivery_slip_detail_middle_classification.material_quantity, material_unit_price: @delivery_slip_detail_middle_classification.material_unit_price, other_cost: @delivery_slip_detail_middle_classification.other_cost, quantity: @delivery_slip_detail_middle_classification.quantity, working_material_name: @delivery_slip_detail_middle_classification.working_material_name, working_middle_item_id: @delivery_slip_detail_middle_classification.working_middle_item_id, working_middle_item_name: @delivery_slip_detail_middle_classification.working_middle_item_name, working_middle_item_short_name: @delivery_slip_detail_middle_classification.working_middle_item_short_name, working_middle_specification: @delivery_slip_detail_middle_classification.working_middle_specification, working_unit_id: @delivery_slip_detail_middle_classification.working_unit_id, working_unit_name: @delivery_slip_detail_middle_classification.working_unit_name, working_unit_price: @delivery_slip_detail_middle_classification.working_unit_price }
    end

    assert_redirected_to delivery_slip_detail_middle_classification_path(assigns(:delivery_slip_detail_middle_classification))
  end

  test "should show delivery_slip_detail_middle_classification" do
    get :show, id: @delivery_slip_detail_middle_classification
    assert_response :success
  end

  test "should get edit" do
    get :edit, id: @delivery_slip_detail_middle_classification
    assert_response :success
  end

  test "should update delivery_slip_detail_middle_classification" do
    patch :update, id: @delivery_slip_detail_middle_classification, delivery_slip_detail_middle_classification: { accessory_cost: @delivery_slip_detail_middle_classification.accessory_cost, delivery_slip_detail_large_classification_id: @delivery_slip_detail_middle_classification.delivery_slip_detail_large_classification_id, delivery_slip_header_id: @delivery_slip_detail_middle_classification.delivery_slip_header_id, delivery_slip_item_division_id: @delivery_slip_detail_middle_classification.delivery_slip_item_division_id, delivery_slip_price: @delivery_slip_detail_middle_classification.delivery_slip_price, execution_price: @delivery_slip_detail_middle_classification.execution_price, execution_quantity: @delivery_slip_detail_middle_classification.execution_quantity, execution_unit_price: @delivery_slip_detail_middle_classification.execution_unit_price, labor_cost_total: @delivery_slip_detail_middle_classification.labor_cost_total, labor_productivity_unit: @delivery_slip_detail_middle_classification.labor_productivity_unit, labor_productivity_unit_total: @delivery_slip_detail_middle_classification.labor_productivity_unit_total, labor_unit_price: @delivery_slip_detail_middle_classification.labor_unit_price, line_number: @delivery_slip_detail_middle_classification.line_number, material_cost_total: @delivery_slip_detail_middle_classification.material_cost_total, material_id: @delivery_slip_detail_middle_classification.material_id, material_id: @delivery_slip_detail_middle_classification.material_id, material_quantity: @delivery_slip_detail_middle_classification.material_quantity, material_unit_price: @delivery_slip_detail_middle_classification.material_unit_price, other_cost: @delivery_slip_detail_middle_classification.other_cost, quantity: @delivery_slip_detail_middle_classification.quantity, working_material_name: @delivery_slip_detail_middle_classification.working_material_name, working_middle_item_id: @delivery_slip_detail_middle_classification.working_middle_item_id, working_middle_item_name: @delivery_slip_detail_middle_classification.working_middle_item_name, working_middle_item_short_name: @delivery_slip_detail_middle_classification.working_middle_item_short_name, working_middle_specification: @delivery_slip_detail_middle_classification.working_middle_specification, working_unit_id: @delivery_slip_detail_middle_classification.working_unit_id, working_unit_name: @delivery_slip_detail_middle_classification.working_unit_name, working_unit_price: @delivery_slip_detail_middle_classification.working_unit_price }
    assert_redirected_to delivery_slip_detail_middle_classification_path(assigns(:delivery_slip_detail_middle_classification))
  end

  test "should destroy delivery_slip_detail_middle_classification" do
    assert_difference('DeliverySlipDetailMiddleClassification.count', -1) do
      delete :destroy, id: @delivery_slip_detail_middle_classification
    end

    assert_redirected_to delivery_slip_detail_middle_classifications_path
  end
end
